Add missing node-red dependency
npm install --save-dev node-red

Without this a fresh clone fails running the example tests:

$ npm run examples

> node-red-node-test-helper@0.3.6 examples
> mocha "examples/**/*_spec.js"

 Exception during run: Error: Cannot find module 'node-red'
Require stack:
- /.../src/github/node-red-node-test-helper/examples/comment_spec.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at Function.resolve (node:internal/modules/helpers:157:19)
    at Object.<anonymous> (/.../src/github/node-red-node-test-helper/examples/comment_spec.js:19:21)
    at Module._compile (node:internal/modules/cjs/loader:1706:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1839:10)
    at Module.load (node:internal/modules/cjs/loader:1441:32)
    at Module._load (node:internal/modules/cjs/loader:1263:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at cjsLoader (node:internal/modules/esm/translators:309:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async formattedImport (/.../src/github/node-red-node-test-helper/node_modules/mocha/lib/nodejs/esm-utils.js:10:14)
    at async Object.requireModule [as requireOrImport] (/.../src/github/node-red-node-test-helper/node_modules/mocha/lib/nodejs/esm-utils.js:102:30)
    at async exports.loadFilesAsync (/.../src/github/node-red-node-test-helper/node_modules/mocha/lib/nodejs/esm-utils.js:152:20)
    at async singleRun (/.../src/github/node-red-node-test-helper/node_modules/mocha/lib/cli/run-helpers.js:168:3)
    at async exports.handler (/.../src/github/node-red-node-test-helper/node_modules/mocha/lib/cli/run.js:379:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/.../src/github/node-red-node-test-helper/examples/comment_spec.js'
  ]
}

$